---
title: "HW2"
author: "Khoa Nguyen"
date: "2/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(gapminder)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

# Excerise 1

## 1.1

Use filter() to subset the gapminder data to three countries of your choice in the 1970’s.


```{r}
filter(gapminder, country %in% c("China", "Japan", "France") & year ==1970:1979)
```

## 1.2

Use the pipe operator %>% to select “country” and “gdpPercap” from your filtered dataset in 1.1.

```{r}
gapminder %>% 
  filter(country %in% c("China", "France", "Japan") & year == 1970:1979) %>% 
  select(country, gdpPercap)
```

## 1.3

```{r}
gapminder %>% 
  mutate(dropLifeExp <- lag(lifeExp))
```

## 1.4

```{r}
gapminder %>% 
  select(country, gdpPercap) %>%
  group_by(country) %>%
  filter(gdpPercap == max(gdpPercap))
```
  
## 1.5

```{r}
gapminder %>% 
  filter(country == "Canada") %>% 
  ggplot() +
  aes(x= lifeExp, y= gdpPercap) +
  geom_point(fill = "red", color = "red", alpha = .5, size = 3) +
  scale_y_continuous(trans = "log10")
```

# Excercise 2

## 2.1

```{r}
library(palmerpenguins)
palmerpenguins::penguins %>% 
  summarize(across(c(body_mass_g, flipper_length_mm),
  list(mean = ~ mean(.x, na.rm = TRUE), 
       sd = ~ sd(.x, na.rm = TRUE),
       min = ~ min(.x, na.rm = TRUE),
       max = ~ max(.x, na.rm = TRUE)))) 

palmerpenguins::penguins %>% 
  ggplot() +
  aes(x = body_mass_g, y = flipper_length_mm) +
  geom_jitter() +
  geom_point(fill = "white", color = "red", alpha = .5,  size = 3)
```

## 2.2

```{r}
palmerpenguins::penguins %>% 
  group_by(species) %>% 
  summarize( 
    total_penguins = n(),
    average_body_mass = mean(body_mass_g, na.rm = TRUE),
    sd_of_body_mass = sd(body_mass_g, na.rm = TRUE),
    average_flipper_length = mean(flipper_length_mm, na.rm = TRUE),
    sd_of_flipper_length = sd(flipper_length_mm, na.rm = TRUE))
```



```{r}
palmerpenguins::penguins %>% 
  ggplot() +
  geom_jitter(height = 1.5, 
              alpha = .5,
              size = 1.0) +
  aes(x = species, y = body_mass_g) +
  geom_point(fill = "black", color = "red", alpha = .5, size = 3)

palmerpenguins::penguins %>% 
  ggplot() +
  aes(body_mass_g) + 
  geom_histogram()
```