---
title: "Final_Proj"
author: "Khoa Nguyen"
date: "3/9/2021"
output:  
  html_document:
    theme: Paper
  gitub_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
```

```{r}
if ( !dir.exists( here::here("Final_project", "data_raw") ) ) {
  dir.create( here::here("Final_project", "data_raw"), recursive = TRUE )
}
```



```{r}
url <- "https://raw.githubusercontent.com/fivethirtyeight/data/master/marriage/divorce.csv"
bothsexes <- "https://raw.githubusercontent.com/fivethirtyeight/data/master/marriage/both_sexes.csv"
men <- "https://raw.githubusercontent.com/fivethirtyeight/data/master/marriage/men.csv"
women <-  "https://raw.githubusercontent.com/fivethirtyeight/data/master/marriage/women.csv"
```

```{r}
Major_data <- read.csv(url,
                       na = c("NA", " ", "-999"))
both_gender <-  read.csv(bothsexes,
                       na = c("NA", " ", "-999"))
men_data <-  read.csv(men,
                       na = c("NA", " ", "-999"))
women_data <-  read.csv(women,
                       na = c("NA", " ", "-999"))
```

```{r}
write.csv(Major_data,
          here::here("Final_project", "data_raw", "Major_data.csv"))
write.csv(both_gender,
          here::here("Final_project", "data_raw", "Both_gender.csv"))
write.csv(men_data,
          here::here("Final_project", "data_raw", "Men_data.csv"))
write.csv(women_data,
          here::here("Final_project", "data_raw", "Women_data.csv"))
```

```{r}
read.csv(
  here::here("Final_Project", "data_raw", "Major_data.csv"))
read.csv(
  here::here("Final_Project", "data_raw", "Both_gender.csv"))
read.csv(
  here::here("Final_Project", "data_raw", "Men_data.csv"))
read.csv(
  here::here("Final_Project", "data_raw", "Women_data.csv"))
```

Summarizing data and observing the marriage trend.

```{r}
both_gender %>% 
  group_by(year) %>% 
  summarize(across(c(HS_2534:BAo_2534),
                      list(mean = ~ mean(.x, na.rm= TRUE),
                sd = ~ sd(.x, na.rm = TRUE),
                min = ~ min(.x, na.rm = TRUE),
                max = ~ max(.x, na.rm = TRUE))))
```

```{r}
tibble_both_gender <- as.tibble(both_gender)
print(tibble_both_gender)
```

Bachelor Degree or higher:
```{r}
tibble_both_gender %>%
  select(year, date, BAp_2534) %>% 
  group_by(year) %>%
  filter(BAp_2534 == max(BAp_2534))
```

As we can see here, the maximum marriage population for people with higher level of education seems to increase over time. This of course is just one variable.
